# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

use_frameworks!

inhibit_all_warnings!

target 'LZJSONDecoder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'LZJSONDecoder', :path => '../'

end
